### ISSUE TITLE
Improve Campaign documentation

### ISSUE THREAD

**Issue by scandella** [putyourlightson/.github#2]
### Which plugin (and version/edition, if appropriate) does this enhancement relate to?
All versions of the Campaign plugin

### Which section of the documentation or concept needs improving and why?
https://putyourlightson.com/plugins/campaign#bounce-and-complaint-handling

### Your suggestions for how to better explain this section or concept.
In the Amazon SES paragraph, you suggested that "Include header" must be enabled for the bounce and complaint handler to work.
[In my experience, this is the opposite that work.](https://github.com/putyourlightson/craft-campaign/issues/424#issuecomment-1758083421)

**Comment by bencroker** [comment]
The docs state that “Include original headers” must be enabled in the SNS topics configuration, which I’m pretty sure is correct. [This comment](https://github.com/putyourlightson/craft-campaign/issues/424#issuecomment-1758083421) refers to “Raw message delivery”, which is something entirely different.

**Comment by scandella** [comment]
You're so right. I was confused.
But unchecked the "Raw message delivery" makes the SNS work for me, whereas leaving it checked did not work. Maybe you should add this advice to the documentation.

**Comment by bencroker** [comment]
I just tested creating a new SNS topic subscription and it appears that `Raw message delivery` is unchecked by default. Since AWS offers so many configuration options, it really only makes sense to document the things that should be changed from the defaults.

![screenshot-h5udqEjD@2x](https://github.com/putyourlightson/.github/assets/57572400/df679e38-e617-410d-acf5-3d0260b4cd69)
